services:
  anime-vue3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anime-vue3-app
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: unless-stopped
    networks:
      - anime-network

networks:
  anime-network:
    driver: bridge
